{% set version = "0.0.0.9003" %}
{% set base = "https://github.com/percyfal/kmer-utils/archive" %}
{% set sha256 = "7fa052019c3bf30cdf9c314776bac8b50241e00e5cbd0c84459c0da094b7a378" %}

package:
  name: kmer-utils
  version: '{{version}}'

source:
  - url: '{{base}}/{{version}}.tar.gz' 
    sha256: '{{sha256}}'                                         

build:
  number: 1
  skip: True  # [win or osx]

requirements:
  build:
    - meson
    - {{ compiler('cxx') }}
  host:
    - kmer-jellyfish 2.*
  run:
    - kmer-jellyfish 2.*

test:
  commands:
    - kmer_count_pairs -h 2>&1 > /dev/null


about:
  home: https://github.com/percyfal/kmer-utils
  license: MIT
  summary: kmer utilities
