{% set version = "0.0.0.9002" %}
{% set base = "https://github.com/percyfal/kmer-utils/archive" %}
{% set sha256 = "b21a0d583baf98fb53a76a043aeb89293bf1c82f66ee656bba80969cc0ee0248" %}

package:
  name: kmer-utils
  version: '{{version}}'

source:
  - url: '{{base}}/{{version}}.tar.gz' 
    sha256: '{{sha256}}'                                         

build:
  number: 1
  skip: True  # [win or osx]

requirements:
  build:
    - meson
    - {{ compiler('cxx') }}
  host:
    - kmer-jellyfish 2.*
  run:
    - kmer-jellyfish 2.*

#test:
#  commands:
#    - kmer_count_pairs 2>&1 > /dev/null


about:
  home: https://github.com/percyfal/kmer-utils
  license: MIT
  summary: kmer utilities
