{% set version = "0.0.0.9014" %}
{% set name = "genecovr" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'
source:
  fn: '{{ version }}.tar.gz'
  url:
    - 'https://github.com/NBISweden/genecovr/archive/0.0.0.9014.tar.gz'
  sha256: b4772dd02d85293fac0045ab9b81ed1106ece73c6e5cba6b4eeeb799ac685869
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tidyr
    - r-viridis
    - r-base
  run:
    - bioconductor-biostrings
    - bioconductor-genomeinfodb
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-biocparallel
    - bioconductor-rtracklayer
    - r-devtools
    - r-dplyr
    - r-ggplot2
    - r-rlang
    - r-tidyr
    - r-viridis
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
    - genecovr
about:
  home: 'https://github.com/NBISweden/genecovr'
  license: GNU General Public License v3.0
  summary: 'Perform gene body coverage analyses in R to evaluate genome assembly quality.'
