on: [push, pull_request]

name: build conda recipes

jobs:
  conda-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-versions: [3.6, 3.7, 3.8]
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: 3.6
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        name: install conda build
        run: mamba install -n root conda-build
      - shell: bash -l {0}
        name: build genecovr
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
          mamba build genecovr --token "$ANACONDA_TOKEN" --user percyfal
