on: [push, pull_request]

name: build conda recipes

jobs:
  conda-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        R-version: ["3.6"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
      - uses: actions/checkout@v2
      - shell: bash -l {0}
        name: install conda build
        run: mamba install -n root conda-build
      - shell: bash -l {0}
        name: build genecovr
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          PYTHON_VERSION: ${{ matrix.python-version }}
          R_VERSION: ${{ matrix.R-version }}
        run: |
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
          echo mamba build --R "$R_VERSION" --python "$PYTHON_VERSION" --token "$ANACONDA_TOKEN" --user percyfal genecovr
          mamba build --R "$R_VERSION" --python "$PYTHON_VERSION" --token "$ANACONDA_TOKEN" --user percyfal genecovr
